In [1]:
%pip install pandas streamlit plotly openpyxl

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Collecting streamlit
  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: plotly in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (6.5.0)
Requirement already satisfied: openpyxl in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (1.9.0)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.0.5-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (8.2.1)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging>=20 in c:\users\user\appdata\roaming\python\python313\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (11.2.1)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (6.33.0)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-23.0.1-cp313-cp313-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: requests<3,>=2.27 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\user\appdata\roaming\python\python313\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from plotly) (2.12.0)
Requirement already satisfied: et-xmlfile in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: jinja2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python313\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.10.5)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.2)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading rpds_py-0.30.0-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.1 MB 5.4 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.1 MB 4.3 MB/s eta 0:00:02
   ------------- -------------------------- 3.1/9.1 MB 5.3 MB/s eta 0:00:02
   ----------------- ---------------------- 3.9/9.1 MB 5.3 MB/s eta 0:00:01
   ---------------------- ----------------- 5.0/9.1 MB 5.2 MB/s eta 0:00:01
   --------------------------- ------------ 6.3/9.1 MB 5.2 MB/s eta 0:00:01
   ------------------------------- -------- 7.1/9.1 MB 5.2 MB/s eta 0:00:01
   ---------------------------------- ----- 7.9/9.1 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 8.7/9.1 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.9/9.1 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 4.1 MB/s eta 0:00:00
Downloading altair-6.0.0-py3-none-any.whl (795 kB)
   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--
   ---------------------------------------  786.4/795.4 kB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 795.4/795.4 kB 3.3 MB/s eta 0:00:00
Downloading cachetools-7.0.5-py3-none-any.whl (13 kB)
Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
Downloading pyarrow-23.0.1-cp313-cp313-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.5 MB 4.5 MB/s eta 0:00:06
   -- ------------------------------------- 1.6/27.5 MB 4.0 MB/s eta 0:00:07
   --- ------------------------------------ 2.6/27.5 MB 4.3 MB/s eta 0:00:06
   ---- ----------------------------------- 3.1/27.5 MB 3.9 MB/s eta 0:00:07
   ---- ----------------------------------- 3.4/27.5 MB 3.8 MB/s eta 0:00:07
   ----- ---------------------------------- 3.9/27.5 MB 3.2 MB/s eta 0:00:08
   ------ --------------------------------- 4.5/27.5 MB 3.2 MB/s eta 0:00:08
   ------- -------------------------------- 5.0/27.5 MB 3.1 MB/s eta 0:00:08
   -------- ------------------------------- 5.8/27.5 MB 3.1 MB/s eta 0:00:07
   --------- ------------------------------ 6.6/27.5 MB 3.2 MB/s eta 0:00:07
   --------- ------------------------------ 6.8/27.5 MB 3.2 MB/s eta 0:00:07
   ---------- ----------------------------- 7.3/27.5 MB 3.0 MB/s eta 0:00:07
   ----------- ---------------------------- 8.1/27.5 MB 3.0 MB/s eta 0:00:07
   ------------ --------------------------- 8.4/27.5 MB 3.0 MB/s eta 0:00:07
   ------------ --------------------------- 8.9/27.5 MB 2.9 MB/s eta 0:00:07
   ------------- -------------------------- 9.4/27.5 MB 2.9 MB/s eta 0:00:07
   -------------- ------------------------- 10.2/27.5 MB 2.9 MB/s eta 0:00:06
   --------------- ------------------------ 10.7/27.5 MB 3.0 MB/s eta 0:00:06
   --------------- ------------------------ 11.0/27.5 MB 2.8 MB/s eta 0:00:06
   ----------------- ---------------------- 11.8/27.5 MB 2.9 MB/s eta 0:00:06
   ------------------ --------------------- 12.6/27.5 MB 2.9 MB/s eta 0:00:06
   ------------------ --------------------- 12.8/27.5 MB 2.9 MB/s eta 0:00:06
   ------------------- -------------------- 13.1/27.5 MB 2.8 MB/s eta 0:00:06
   ------------------- -------------------- 13.4/27.5 MB 2.7 MB/s eta 0:00:06
   -------------------- ------------------- 14.2/27.5 MB 2.8 MB/s eta 0:00:05
   --------------------- ------------------ 14.9/27.5 MB 2.8 MB/s eta 0:00:05
   ---------------------- ----------------- 15.5/27.5 MB 2.8 MB/s eta 0:00:05
   ----------------------- ---------------- 16.0/27.5 MB 2.8 MB/s eta 0:00:05
   ----------------------- ---------------- 16.3/27.5 MB 2.8 MB/s eta 0:00:05
   ------------------------ --------------- 17.0/27.5 MB 2.8 MB/s eta 0:00:04
   ------------------------- -------------- 17.8/27.5 MB 2.8 MB/s eta 0:00:04
   -------------------------- ------------- 18.4/27.5 MB 2.8 MB/s eta 0:00:04
   --------------------------- ------------ 19.1/27.5 MB 2.8 MB/s eta 0:00:03
   ---------------------------- ----------- 19.9/27.5 MB 2.8 MB/s eta 0:00:03
   ----------------------------- ---------- 20.2/27.5 MB 2.8 MB/s eta 0:00:03
   ------------------------------ --------- 20.7/27.5 MB 2.8 MB/s eta 0:00:03
   ------------------------------ --------- 21.2/27.5 MB 2.8 MB/s eta 0:00:03
   ------------------------------- -------- 22.0/27.5 MB 2.8 MB/s eta 0:00:02
   --------------------------------- ------ 22.8/27.5 MB 2.8 MB/s eta 0:00:02
   --------------------------------- ------ 23.3/27.5 MB 2.8 MB/s eta 0:00:02
   ----------------------------------- ---- 24.4/27.5 MB 2.9 MB/s eta 0:00:02
   ------------------------------------ --- 25.2/27.5 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 25.7/27.5 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 26.5/27.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  27.5/27.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 2.9 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.9 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.9 MB 1.7 MB/s eta 0:00:04
   ------ --------------------------------- 1.0/6.9 MB 2.0 MB/s eta 0:00:03
   ------------ --------------------------- 2.1/6.9 MB 2.8 MB/s eta 0:00:02
   ---------------- ----------------------- 2.9/6.9 MB 3.2 MB/s eta 0:00:02
   ------------------- -------------------- 3.4/6.9 MB 3.1 MB/s eta 0:00:02
   ------------------------ --------------- 4.2/6.9 MB 3.0 MB/s eta 0:00:01
   ------------------------ --------------- 4.2/6.9 MB 3.0 MB/s eta 0:00:01
   --------------------------- ------------ 4.7/6.9 MB 2.7 MB/s eta 0:00:01
   ------------------------------ --------- 5.2/6.9 MB 2.7 MB/s eta 0:00:01
   --------------------------------- ------ 5.8/6.9 MB 2.7 MB/s eta 0:00:01
   ------------------------------------ --- 6.3/6.9 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 6.9/6.9 MB 2.7 MB/s eta 0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-0.30.0-cp313-cp313-win_amd64.whl (240 kB)
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Installing collected packages: watchdog, toml, tenacity, smmap, rpds-py, pyarrow, cachetools, attrs, referencing, pydeck, gitdb, jsonschema-specifications, gitpython, jsonschema, altair, streamlit
Successfully installed altair-6.0.0 attrs-26.1.0 cachetools-7.0.5 gitdb-4.0.12 gitpython-3.1.46 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 pyarrow-23.0.1 pydeck-0.9.1 referencing-0.37.0 rpds-py-0.30.0 smmap-5.0.3 streamlit-1.56.0 tenacity-9.1.4 toml-0.10.2 watchdog-6.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

df = pd.read_excel(
    "DATA DASHBOARD HRD PT ALDZAMA.xlsx",
    sheet_name="INTERNSHIP",
    skiprows=2,     # karena mulai dari baris 3
    usecols="B:L"   # sesuaikan jumlah kolom kamu
)

df.columns = [
    "nama", "program", "institusi", "kota", "ket",
    "permohonan", "penempatan", "durasi",
    "status", "final_project", "potensi"
]

df.head()

,nama,program,institusi,kota,ket,permohonan,penempatan,durasi,status,final_project,potensi
0,Rizka Aulya,Bisnis Digital,Universitas Negeri Surabaya,Surabaya,Kuliah,2025-08-01,HR,25 Agustus - 31 Desember 2025,Onboard,Dashboard HRD & Manual Book Onboarding,NaN
1,Bilal Ramadhan,Teknologi Informasi,Universitas Negeri Surabaya,Surabaya,Kuliah,2025-09-01,Exim,15 Sept 2025 - 15 Januari 2026,Selesai,NaN,NaN
2,Razeh Nurebikasyahaq,Teknologi Rekayasa Manufaktur,ITS,Surabaya,Kuliah,2025-12-01,Engineer,13 Desember 2025 - 22 Februari 2026,Selesai,Dashboard Fleet Management for Maintenance Mon...,NaN
3,Fatya Zahidah,PKK,USK,Banda Aceh,Kuliah,2025-12-01,Sales,23 Desember 2025 - 23 Januari 2026,Onboard,NaN,NaN
4,Achmad Hardinata,Teknik Permesinan,SMK Nurul Islam,Gresik,SMK,2026-01-01,Fabrikasi,05 Januari 2026 - 30 Juni 2026,Onboard,NaN,NaN

In [2]:
# ubah permohonan jadi datetime
df['permohonan'] = pd.to_datetime(df['permohonan'], errors='coerce')

# ambil bulan
df['bulan'] = df['permohonan'].dt.to_period('M').astype(str)

In [3]:
# 1. jumlah per institusi
institusi = df['institusi'].value_counts().reset_index()
institusi.columns = ['institusi', 'jumlah']

# 2. permohonan per bulan
permohonan = df['bulan'].value_counts().sort_index().reset_index()
permohonan.columns = ['bulan', 'jumlah']

# 3. status intern
status = df['status'].value_counts().reset_index()
status.columns = ['status', 'jumlah']

In [1]:
FILE_PATH = "DATA DASHBOARD HRD PT ALDZAMA.xlsx"

In [1]:
import pandas as pd

FILE_PATH = "DATA DASHBOARD HRD PT ALDZAMA.xlsx"

# BACA DATA
df = pd.read_excel(
    FILE_PATH,
    sheet_name="MAN POWER",
    usecols="B:H"
)

# RENAME KOLOM
df.columns = [
    "nama",
    "jenis_kelamin",
    "jabatan",
    "branch",
    "group_project",
    "ring",
    "status_kontrak"
]

# LIHAT DATA
df.head()

,nama,jenis_kelamin,jabatan,branch,group_project,ring,status_kontrak
0,Agus Jayana,NaN,DIREKSI,HO,Head Office,NaN,Permanent
1,Hendar Sulaeman,NaN,DIREKSI,HO,Head Office,NaN,Permanent
2,Muhammad Achyad,NaN,DIREKSI,HO,Head Office,NaN,Permanent
3,"Zulkarnaini, ST",NaN,DIREKSI,HO,Head Office,NaN,Permanent
4,Rizky Hidayat,NaN,DIREKSI,HO,Head Office,NaN,Permanent

In [2]:
df['jabatan'] = df['jabatan'].astype(str).str.strip()
df['branch'] = df['branch'].astype(str).str.strip()
df['group_project'] = df['group_project'].astype(str).str.strip()
df['status_kontrak'] = df['status_kontrak'].astype(str).str.strip().str.lower()

In [3]:
total = len(df)
permanent = len(df[df['status_kontrak'] == 'permanent'])
kontrak = len(df[df['status_kontrak'] == 'kontrak'])

print(total, permanent, kontrak)

570 33 286

In [4]:
df['jabatan'].value_counts()

jabatan
nan                          231
HELPER                        51
STAFF                         44
OPERATOR                      31
Helper                        21
Semi skill                    17
SUPERVISOR/LEADER/ADVISOR     15
Skill brick                   12
Scaffolder                     9
Driver                         9
Vacuum Operator                7
Electrical Technician          6
Supervisor Project             6
MANAGER                        6
Safety Officer                 6
Mechanical Technician          6
DIREKSI                        6
Shift Engineer                 5
Admin Project                  5
Helper Scaffolder              5
DRIVER                         5
Operator Excavator             4
Vacuum Truck Driver            4
Instrument Technician          4
Mentor Tapper Skimmer          4
Dump Truck Driver              4
Safety officer                 4
Foreman                        3
Skill Brick Layer              3
Safety                         3
Material Control               2
Site Manager                   2
Safety Refractory              2
Advisor                        2
SUPPORTING                     2
welder                         2
Demolish                       1
PJO                            1
Team Leader Scaffolding        1
Admin                          1
Driver Scaffolder              1
Admin Scaffolding              1
Admin Safety                   1
Safety Koordinator             1
fitter                         1
technical engineer             1
Staff Exim                     1
Staff                          1
Staff Admin                    1
Safety Representatif           1
Semi Skill                     1
Opr. forklift                  1
Fitter                         1
Fitter/Semi Skill              1
Safety Representative          1
Administrator                  1
Mekanik                        1
Driver Light Vehicle           1
Name: count, dtype: int64

In [5]:
df['branch'].value_counts()

branch
HO                                 112
Aldzama - Refractory                86
Aldzama-Antam Lining                85
Aldzama - HOTMETAL                  55
Aldzama-Vale                        44
Aldzama-Antam Electrode Casing      33
HO/Fabrikasi Site&WS                23
Aldzama - Scaffolding               21
Aldzama - Lime Package              19
Aldzama - Excavator & DT Rental     17
Aldzama-Vacuum PTFI                 16
HO/Hydraulic                        12
Aldzama-CMP                         11
Aldzama-Vacuum Antam                10
Aldzama-Smelting ASD & Others        9
Aldzama - Tapper Skimmer             4
HO/Security                          4
Aldzama - Safety Signage             3
HO - Fabrikasi                       2
Aldzama - Komodo PTFI                2
HO / Hydraulic                       1
HO / Fabrikasi                       1
Name: count, dtype: int64

In [6]:
df['group_project'].value_counts()

group_project
PT Freeport Indonesia       225
Head Office                 153
PT ANTAM                    128
PT Vale Indonesia            44
PT Ceria Metalindo Prima     11
PT SMELTING                   9
Name: count, dtype: int64

In [7]:
df['status_kontrak'].value_counts()

status_kontrak
kontrak      286
nan          251
permanent     33
Name: count, dtype: int64

In [8]:
FILE_PATH = "DATA DASHBOARD HRD PT ALDZAMA.xlsx"

df_gaji = pd.read_excel(
    FILE_PATH,
    sheet_name="GAJI DAN PPH21",
    usecols="B:D",
    skiprows=2
)

df_gaji.columns = ["project", "periode", "gaji"]

df_gaji.head()

            project    periode         gaji
0   HO Administrasi 2026-01-30  651568361.0
1       HO Demolish 2026-01-30  266661654.0
2    Safety Signage 2026-01-30     471429.0
3  Scaffolding-PTFI 2026-01-30  169770500.0
4        Vale Ladle 2026-01-30  442322379.0

In [9]:
df_pph = pd.read_excel(
    FILE_PATH,
    sheet_name="GAJI DAN PPH21",
    usecols="G:I",
    skiprows=2
)

df_pph.columns = ["project", "periode", "pph21"]

df_pph.head()

                            project    periode     pph21
0  Aldzama - Antam Electrode Casing 2026-01-30  216250.0
1            Aldzama - Antam Lining 2026-01-30  975750.0
2       Aldzama - Asset Maintenance 2026-01-30   80000.0
3                     Aldzama - CMP 2026-01-30   13750.0
4                Aldzama - Demolish 2026-01-30   53250.0

In [10]:
total_gaji = df_gaji['gaji'].sum()
total_pph21 = df_pph['pph21'].sum()
jumlah_project = df_gaji['project'].nunique()

print("Total Gaji:", total_gaji)
print("Total PPH21:", total_pph21)
print("Jumlah Project:", jumlah_project)

Total Gaji: 8697699434.0
Total PPH21: 11791500.0
Jumlah Project: 21

In [11]:
FILE_PATH = "DATA DASHBOARD HRD PT ALDZAMA.xlsx"

df = pd.read_excel(
    FILE_PATH,
    sheet_name="INTERNAL & EXTERNAL TRAINING FE",
    usecols="B:H"
)

df.columns = [
    "jenis",
    "nama",
    "divisi",
    "pelatihan",
    "lembaga",
    "periode",
    "status"
]

df.head()

,jenis,nama,divisi,pelatihan,lembaga,periode,status
0,External,Christian Bagaskara Wibisono,Sales Engineer,POP,Donya Fatar,2026-01-10,Done
1,External,Muhammad Qowiy Akbar,Refractory,POP,Donya Fatar,2026-01-10,Done
2,External,Husen Nugraha,Refractory,POP,Donya Fatar,2026-01-10,Done
3,External,Thubagus Ahmad Mananta,Refractory,POP,Donya Fatar,2026-01-10,Done
4,External,Gideon Pambudi Laksono,Refractory,POP,Donya Fatar,2026-01-25,Done

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   jenis      42 non-null     object
 1   nama       42 non-null     object
 2   divisi     42 non-null     object
 3   pelatihan  42 non-null     object
 4   lembaga    42 non-null     object
 5   periode    24 non-null     datetime64[ns]
 6   status     42 non-null     object
dtypes: datetime64[ns](1), object(6)
memory usage: 2.4+ KB

In [15]:
total = len(df)
internal = len(df[df['jenis'] == 'Internal'])
external = len(df[df['jenis'] == 'External'])

done = len(df[df['status'] == 'Done'])
progress = len(df[df['status'] == 'In Progress'])
cancel = len(df[df['status'] == 'Cancel'])

print("Total:", total)
print("Internal:", internal)
print("External:", external)
print("Done:", done)
print("Progress:", progress)
print("Cancel:", cancel)

Total: 42
Internal: 1
External: 41
Done: 14
Progress: 13
Cancel: 9

In [16]:
FILE_PATH = "DATA DASHBOARD HRD PT ALDZAMA.xlsx"

df_karyawan = pd.read_excel(
    FILE_PATH,
    sheet_name="BPJS",
    usecols="B:D"
)

df_karyawan.columns = ["nama", "project", "jenis_bpjs"]

df_karyawan.head()

                     nama           project      jenis_bpjs
0   .ANDI AHSAN CHALID,MT  ELECTRODE CASING  BPJS Kesehatan
1         ABDULLAH HANAFI                HO  BPJS Kesehatan
2      ABDULLAH NUR HIKAM    SAFETY SIGNAGE  BPJS Kesehatan
3        ABRORI ROMADHONI          HOTMETAL  BPJS Kesehatan
4  ACHFANI CATUR MURIAWAN                HO  BPJS Kesehatan

In [17]:
df_karyawan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nama        1093 non-null   object
 1   project     1093 non-null   object
 2   jenis_bpjs  1093 non-null   object
dtypes: object(3)
memory usage: 25.7+ KB

In [18]:
df_karyawan['project'] = df_karyawan['project'].astype(str).str.strip()
df_karyawan['jenis_bpjs'] = df_karyawan['jenis_bpjs'].astype(str).str.strip().str.lower()

df_karyawan.head()

                     nama           project      jenis_bpjs
0   .ANDI AHSAN CHALID,MT  ELECTRODE CASING  bpjs kesehatan
1         ABDULLAH HANAFI                HO  bpjs kesehatan
2      ABDULLAH NUR HIKAM    SAFETY SIGNAGE  bpjs kesehatan
3        ABRORI ROMADHONI          HOTMETAL  bpjs kesehatan
4  ACHFANI CATUR MURIAWAN                HO  bpjs kesehatan

In [19]:
df_kesehatan = pd.read_excel(
    FILE_PATH,
    sheet_name="BPJS",
    usecols="G:H"
)

df_kesehatan.columns = ["periode", "pembayaran"]

df_kesehatan.head()

     periode   pembayaran
0 2025-12-10  109044014.0
1 2026-01-10  113523374.0
2 2026-02-10  117336911.0
3 2026-03-10  115642490.0
4 2026-04-10          NaN

In [ ]:
df_kesehatan['periode'] = df_kesehatan['periode'].astype(str).str.strip()


df_kesehatan['pembayaran'] = (
    df_kesehatan['pembayaran']
    .astype(str)
    .str.replace('.', '', regex=False)
)

df_kesehatan['pembayaran'] = pd.to_numeric(df_kesehatan['pembayaran'], errors='coerce')

df_kesehatan

         periode    pembayaran
0     2025-12-10  1.090440e+09
1     2026-01-10  1.135234e+09
2     2026-02-10  1.173369e+09
3     2026-03-10  1.156425e+09
4     2026-04-10           NaN
...          ...           ...
1088         NaT           NaN
1089         NaT           NaN
1090         NaT           NaN
1091         NaT           NaN
1092         NaT           NaN

[1093 rows x 2 columns]

In [21]:
df_tk1 = pd.read_excel(
    FILE_PATH,
    sheet_name="PAY BPJS TK",
    usecols="C:D"
)

df_tk1.columns = ["periode", "pembayaran"]

df_tk1.head()

     periode   pembayaran
0 2025-11-10  238321622.0
1 2025-12-10  225828871.0
2 2026-01-10  210198021.0
3 2026-02-10  215526951.0
4 2026-03-10          NaN

In [22]:
df_tk2 = pd.read_excel(
    FILE_PATH,
    sheet_name="PAY BPJS TK",
    usecols="F:G"
)

df_tk2.columns = ["periode", "pembayaran"]

df_tk2.head()

     periode  pembayaran
0 2025-11-10   5358018.0
1 2025-12-10   3740184.0
2 2026-01-10   4506447.0
3 2026-02-10   5922303.0
4 2026-03-10         NaN

In [45]:
import pandas as pd

FILE_PATH = "DATA DASHBOARD HRD PT ALDZAMA.xlsx"

try:
    # =====================
    # TABEL 1 - OVERTIME
    # =====================
    df_overtime = pd.read_excel(
        FILE_PATH,
        sheet_name="OVERTIME DAN ABSENSI",
        usecols="B:D",
        skiprows=2
    )
    df_overtime.columns = ["project", "bulan", "overtime"]


    # =====================
    # TABEL 2 - ABSENSI
    # =====================
    df_absensi = pd.read_excel(
        FILE_PATH,
        sheet_name="OVERTIME DAN ABSENSI",
        usecols="F:G",
        skiprows=2
    )
    df_absensi.columns = ["periode", "absensi"]


    # =====================
    # TABEL 3 - COST
    # =====================
    df_cost = pd.read_excel(
        FILE_PATH,
        sheet_name="OVERTIME DAN ABSENSI",
        usecols="I:M",
        skiprows=2
    )
    df_cost.columns = [
        "project",
        "bulan",
        "total_cost",
        "overtime_cost",
        "overtime_percent"
    ]


    # =====================
    # TAMPILKAN HASIL
    # =====================
    print("✅ OVERTIME")
    print(df_overtime.head(), "\n")

    print("✅ ABSENSI")
    print(df_absensi.head(), "\n")

    print("✅ COST")
    print(df_cost.head(), "\n")

except Exception as e:
    print("❌ ERROR:", e)

✅ OVERTIME
           project      bulan  overtime
0  HO Administrasi 2026-01-20      0.05
1  HO Administrasi 2026-02-20      0.03
2  HO Administrasi 2026-03-20       NaN
3  HO Administrasi 2026-04-20       NaN
4  HO Administrasi 2026-05-20       NaN

✅ ABSENSI
     periode  absensi
0 2026-01-02    0.894
1 2026-01-03      NaN
2 2026-01-04      NaN
3 2026-01-05    0.901
4 2026-01-06    0.915

✅ COST
           project                bulan   total_cost overtime_cost  \
0  HO Administrasi  2026-01-26 00:00:00  542,600,000    27,905,650
1  HO Administrasi  2026-02-26 00:00:00  544,818,182    16,840,395
2  HO Administrasi  2026-03-26 00:00:00          NaN           NaN
3  HO Administrasi  2026-04-26 00:00:00          NaN           NaN
4  HO Administrasi               May-26          NaN           NaN

   overtime_percent
0              0.05
1              0.03
2               NaN
3               NaN
4               NaN

In [6]:
import pandas as pd

FILE_PATH = "DATA DASHBOARD HRD PT ALDZAMA.xlsx"

In [7]:
df_mcu = pd.read_excel(
    FILE_PATH,
    sheet_name="MCU FEB 2026",
    usecols="B:H"
)

df_mcu.columns = [
    "nama",
    "divisi",
    "project",
    "tahun",
    "periode",
    "tipe_mcu",
    "hasil_mcu"
]

# CLEANING
df_mcu['nama'] = df_mcu['nama'].astype(str).str.strip()
df_mcu['project'] = df_mcu['project'].astype(str).str.strip()
df_mcu['hasil_mcu'] = df_mcu['hasil_mcu'].astype(str).str.strip().str.lower()

df_mcu['periode'] = pd.to_datetime(df_mcu['periode'], errors='coerce')

df_mcu.head(20)

,nama,divisi,project,tahun,periode,tipe_mcu,hasil_mcu
0,Shirra Ulfia Irham,QMS & Audit,HO,2026,2026-02-11,MCU lengkap,fit/fit with note
1,Achmad Radifan R,Procurement,HO,2026,2026-02-11,MCU lengkap,fit/fit with note
2,Muhammad Yusuf Shofyan,HRD,HO,2026,2026-02-11,MCU lengkap,fit/fit with note
3,Rakhshandrina Kaysa Syifa Desler,Safety,HO,2026,2026-02-11,MCU lengkap,fit/fit with note
4,Joni,Ad-hoc,HO,2026,2026-02-11,MCU lengkap,fit/fit with note
5,Kevin Kresno,Sales Trading,HO,2026,2026-03-13,MCU lengkap,fit/fit with note
6,Ahmad Badrul arif,Finance & Accounting Tax,HO,2026,2026-03-13,MCU lengkap,fit/fit with note
7,Diana Aulia Rahma,Warehouse,HO,2026,2026-03-13,MCU lengkap,fit/fit with note
8,Rahadian Nur Fauzi,Procurement,HO,2026,2026-03-13,MCU lengkap,fit/fit with note
9,Muhammad Ridho Mujahid,Legal,HO,2026,2026-03-13,MCU lengkap,fit/fit with note
10,Khoirun Nisak,Limepackage,nan,2026,2026-01-30,NaN,fit/fit with note
11,Rovi Maulidani Syela,Limepackage,nan,2026,2026-02-23,NaN,fit/fit with note
12,Sutarsono,Antam,nan,2026,2026-01-28,NaN,fit/fit with note
13,Sri Nugraha,Antam Vacuum,nan,2026,2026-02-16,NaN,fit/fit with note
14,Jumadi,Antam Vacuum,nan,2026,2026-02-15,NaN,fit/fit with note
15,Wisnu Budi Trinugroho,Antam Vacuum,nan,2026,2026-02-15,NaN,fit/fit with note
16,Firmansyah,Antam Vacuum,nan,2026,2026-02-15,NaN,fit/fit with note
17,Akbar Setyawan,Antam Vacuum,nan,2026,2026-02-15,NaN,fit/fit with note
18,Ahmad Anwar Mufarriz,Scaffolding,nan,2026,2026-02-09,NaN,fit/fit with note
19,Muhamad Abdul Aziz Al ghazali,Scaffolding,nan,2026,2026-02-09,NaN,fit/fit with note

In [8]:
df_karyawan = pd.read_excel(
    FILE_PATH,
    sheet_name="MCU FEB 2026",
    usecols="K:O"
)

df_karyawan.columns = [
    "nama",
    "branch",
    "job",
    "ring",
    "gender"
]

# CLEANING
df_karyawan['nama'] = df_karyawan['nama'].astype(str).str.strip()
df_karyawan['branch'] = df_karyawan['branch'].astype(str).str.strip()
df_karyawan['job'] = df_karyawan['job'].astype(str).str.strip()
df_karyawan['gender'] = df_karyawan['gender'].astype(str).str.strip().str.lower()

df_karyawan.head()

                 nama                    branch     job ring gender
0        Abdul Miftah  Aldzama - Safety Signage   Skill    1   male
1          Abdul Muiz        Aldzama - HOTMETAL   Skill    1   male
2     Abdullah Hanafi        Aldzama - HOTMETAL  Helper    2   male
3  Abdullah Nur Hikam  Aldzama - Safety Signage  Helper    2   male
4    Abrori Romadhoni        Aldzama - HOTMETAL   Skill    2   male

In [9]:
df_pay_pivot = pd.read_excel(
    FILE_PATH,
    sheet_name="Pay MCU 2026",
    usecols="A:O"
)

df_pay_pivot.head()

,User,Project,2025-01-25 00:00:00,2025-02-25 00:00:00,2025-03-25 00:00:00,2025-04-25 00:00:00,2025-05-25 00:00:00,2025-06-25 00:00:00,2025-07-25 00:00:00,2025-08-25 00:00:00,2025-09-25 00:00:00,2025-10-25 00:00:00,2025-11-25 00:00:00,2025-12-25 00:00:00,Grand Total
0,Antam,ANTAM - Fabrikasi Electrode Casing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3090000.0,NaN,NaN,NaN,NaN,3090000.0
1,NaN,"ANTAM - Refractory Lining, Slag Pot Demolition...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1970000.0,NaN,30000.0,160000.0,2160000.0
2,Freeport,Freeport - Brick Layer Skilled Manpower II,NaN,1797000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1797000.0
3,NaN,Freeport - BVI Manpower Specialist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,320000.0,NaN,NaN,320000.0
4,NaN,Freeport - BVI Manpower Supply Labour,NaN,NaN,NaN,NaN,NaN,NaN,4650300.0,2964250.0,NaN,NaN,NaN,8482880.0,16097430.0

In [10]:
df_pay_summary = pd.read_excel(
    FILE_PATH,
    sheet_name="Pay MCU 2026",
    usecols="P:Q"
)

df_pay_summary.columns = ["user", "total"]

df_pay_summary.head()

       user         total
0     ANTAM  5.250000e+06
1  FREEPORT  2.146161e+09
2        HO  1.222794e+07
3       MTI  1.125500e+07
4       PTS  2.326094e+06

In [11]:
df_pay = pd.read_excel(
    FILE_PATH,
    sheet_name="Pay MCU 2026",
    usecols="T:W"
)

df_pay.columns = [
    "user",
    "project",
    "periode",
    "pembayaran"
]

df_pay.head()

,user,project,periode,pembayaran
0,Antam,ANTAM - Fabrikasi Electrode Casing,2025-01-01,NaN
1,NaN,"ANTAM - Refractory Lining, Slag Pot Demolition...",2025-01-01,NaN
2,Freeport,Freeport - Brick Layer Skilled Manpower II,2025-01-01,NaN
3,NaN,Freeport - BVI Manpower Specialist,2025-01-01,NaN
4,NaN,Freeport - BVI Manpower Supply Labour,2025-01-01,NaN

In [12]:
# CLEAN STRING
df_pay['user'] = df_pay['user'].astype(str).str.strip()
df_pay['project'] = df_pay['project'].astype(str).str.strip()
df_pay['periode'] = df_pay['periode'].astype(str).str.strip()

# CLEAN UANG (Rp)
df_pay['pembayaran'] = (
    df_pay['pembayaran']
    .astype(str)
    .str.replace('Rp', '')
    .str.replace('.', '', regex=False)
)

df_pay['pembayaran'] = pd.to_numeric(df_pay['pembayaran'], errors='coerce')

# DROP YANG TIDAK ADA NILAI
df_pay = df_pay.dropna(subset=['pembayaran'])

df_pay.head()

,user,project,periode,pembayaran
25,MTI,MTI - Roaster Demolition Merdeka Tsingshan Ind...,2025-01-01,112550000.0
33,nan,Vale - Ladle Cleaning,2025-01-01,20060000.0
36,Freeport,Freeport - Brick Layer Skilled Manpower II,2025-02-01,17970000.0
39,nan,Freeport - Excavator and Dump Truck Rental,2025-02-01,387376580.0
41,nan,Freeport - General Site Services Housekeeping FMR,2025-02-01,89923510.0

In [13]:
print("MCU:", df_mcu.shape)
print("Karyawan:", df_karyawan.shape)
print("Pay MCU:", df_pay.shape)

MCU: (550, 7)
Karyawan: (550, 5)
Pay MCU: (104, 4)